### ISSUE TITLE
Repeatable Fields not working

### ISSUE THREAD

**Issue by kellygrape** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#15]
Working off the most recent version, I'm trying to include a metabox that has a set of reusable fields, allowing the user to upload an image and set a caption, and do this for as many image/captions as they wish.

When including the full sample.php code, everything seems to work fine until I remove the "jQuery UI Date input" and the "jQuery UI Slider" sample fields.  Once these are removed, neither the repeatable nor the image uploader work (not even an image uploader outside of the repeat block).

It appears that if you do not include one or both of the UI fields, the jquery needed for the image field and the repeating is not loaded correctly.

I'd try to fork and fix this, but I'm not quite sure where to begin.

**Comment by arlodesign** [comment]
I can confirm this issue. The scripts are not being enqueued because meta_box_find_field_type() is always returning false when `'type'` is `'repeatable'`. In that case, the function then recursively looks for the `'repeatable'` field type in the `'repeatable_fields'` array. To fix this, I put a check at the beginning of the loop for the field type. It has an additional advantage of not looping through the repeatable fields every time. I'm not 100% sure yet this will work in every case (just started playing with this library), but it's working for me now.

``` php
function meta_box_find_field_type( $needle, $haystack ) {
    foreach ( $haystack as $h ) {
        if ( isset( $h['type'] ) && $h['type'] == $needle )
            return true;

        if ( isset( $h['type'] ) && $h['type'] == 'repeatable' )
            return meta_box_find_field_type( $needle, $h['repeatable_fields'] );
    }
    return false;
}
```

**Comment by tammyhart** [comment]
@arlodesign Thanks for trying to find a fix, but that creates an issue where the function won't look through the repeatable fields to see what is in them. The reason we need it to look deeper is because you may have something like a slider or chosen field within there that needs additional scripts. I've added a workaround for just finding a repeatable field, see docs for more explanation.

@kellygrape Thanks for finding the lack of image support. The last query for scripts wasn't sniffing out the image field but I've added this back in now.

Let me know if you run into any more issues!
